
name: Brim.io

description: Code, travels, unsolicited advice

meta_description: "Your New Jekyll Site, Blogging about stuffs"

baseurl: "/" # the subpath of your site, e.g. /blog/

url: "http://www.brim.io" # the base hostname & protocol for your site
email: brimizer@gmail.com
twitter_username: brimizer
github_username:  brimizer

# Build settings
markdown: kramdown
markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
